### ISSUE TITLE
Documentation for usage and configuration

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#1]
We more or less completely neglected this for the v0.1 release.

**Comment by ruscur** [comment]
The "Installation" README section is a start, and reading the example file helps too.  I think any motivated person could probably figure it out, though we absolutely need something better than we have now.

**Comment by ajdlinux** [comment]
This was a direct request from the one person who responded to my message on #rust announcing snowpatch :p

**Comment by ajdlinux** [comment]
Should include docopt info and mention that example configs exist
