### ISSUE TITLE
snowpatch exits before calling Jenkins jobs

### ISSUE THREAD

**Issue by ruscur** [ruscur/snowpatch#11]
In run modes that aren't endless (like `--series` or `--count`) snowpatch can end before starting a Jenkins job.  These modes shouldn't be sending results to Patchwork, so instead of calling a Jenkins job and polling for it, they should make a Jenkins job, link the URL then die.

**Comment by ajdlinux** [comment]
Is this actually an issue? From what I can tell, `--series` and `--count` actually *do* post results to Patchwork, only `--patch` doesn't (for obvious reasons).
