### ISSUE TITLE
Submit Jenkins test results to patchwork

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#14]

**Comment by ajdlinux** [comment]
Working on this!

**Comment by ajdlinux** [comment]
@ruscur: what exactly do we want to capture from Jenkins? Console output is the obvious option here...

**Comment by ruscur** [comment]
I don't know.  At the very least, the status.  Jenkins has pass/fail, it also has an inbetween state that I think might be from a plugin that we could support too.  Console output is something we might want to make configurable for cases where the jenkins instance isn't accessible to people looking at patchwork, but if it is accessible you could just link to the job.
