### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#15]

**Comment by ajdlinux** [comment]
As of be36677963eaccffeeb2e5d9b43956fd099a8e7a we now use the Rust logging framework for our existing error messages. I'm going to close this issue for now, unless @ruscur objects - there are probably a few more log messages we need to add though.

**Comment by ruscur** [comment]
Yeah let's just add more log messages as we change stuff.  We should definitely have more debug messages scattered throughout, and probably some trace of data.  I only just realised we can get hyper to tell us everything it tries to do, which I wish I'd known about before...
