### ISSUE TITLE
Enable the ability to go to page 2 (and beyond) of Patchwork results

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#17]
Right now all we test is what's on the first "page" of JSON results from Patchwork. This is fine for daemon-mode, but if you wanted to test the last 300 series, we'd need to be able to go back a few pages.

**Comment by ajdlinux** [comment]
@ruscur How do we work out how many pages back we want to go?

**Comment by ajdlinux** [comment]
RFC patch submitted

**Comment by ruscur** [comment]
I think we should have a config option under [patchwork] describing how far back the series history to go.  Maybe default to 100?

Unless you have a better idea.

**Comment by ruscur** [comment]
something something pagination

**Comment by ajdlinux** [comment]
This really is a bug, not an enhancement. Retagged accordingly.

Negotiating with Patchwork upstream about how we want to do pagination.

**Comment by ajdlinux** [comment]
What do we want to do here?

**Comment by ruscur** [comment]
I think we just do it but only if count is specified?  Build a list at the start then iterate through them without touching the API
