### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by ruscur** [ruscur/snowpatch#21]
Currently snowpatch can't deal with not being able to get where it needs to go, and doesn't look at something like `https_proxy`.

Blocked on hyperium/hyper#531, which I believe is blocked on async support in hyper.

**Comment by ruscur** [comment]
No longer blocked, patch sent

**Comment by ajdlinux** [comment]
Discussion at http://patchwork.ozlabs.org/patch/619716/

**Comment by ajdlinux** [comment]
Closed by 7e76a0c2126c2a8c577706bd35a5b143c69d419b
