### ISSUE TITLE
Patch application can fail if snowpatch tries to apply patch after maintainer has merged

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#24]

**Comment by ajdlinux** [comment]
@ruscur any ideas what the easiest way to detect this situation would be?

**Comment by ruscur** [comment]
We could keep an in-memory (or write to a file) skiplist of IDs, with the
assumption that we can't trust patchwork.

**Comment by amboar** [comment]
`git patch-id` or `git cherry` might be useful here

**Comment by ruscur** [comment]
It's tricky.  I think `git patch-id` will fail if the maintainer made any minor changes before merging, and `git cherry` won't be useful since we are branching directly from the target before applying patches.

We probably *should* do something around this, but it's pretty low prio.

**Comment by ajdlinux** [comment]
As we've discussed, this is low-priority, so I'm deferring this indefinitely

**Comment by ajdlinux** [comment]
Retagging this as an enhancement because it was never a bug

**Comment by ajdlinux** [comment]
My current thought on how we could handle this, inspired by sfr's linux-next warning emails: if we fail to apply, just check the git log for a commit with an identical title, and if found, report the apply_patch check as a warning rather than a failure
