### ISSUE TITLE
Implement support for new upstream Patchwork API

### ISSUE THREAD

**Issue by ruscur** [ruscur/snowpatch#29]
snowpatch fundamentally requires series support and test reporting in patchwork.  For this reason, we have used the freedesktop.org fork, which is slowing in activity, while the "upstream"/"official" patchwork just got a REST API and series support has been posted to the list.  There are going to be differences, and it would be good to identify the pain points now.

We should attempt to get a patchwork instance running, with the series support applied, and see how much we can snowpatch it.

**Comment by ajdlinux** [comment]
If we can get it working, I am quite happy to drop support for fd.o Patchwork in favour of the support that's on the upstream list.

**Comment by ruscur** [comment]
I think it depends on how different things turn out to be.  If they're wildly different, then sure.  If not, then it's good to set things up to support different APIs for when upstream patchwork inevitably has backwards incompatible API changes.

**Comment by ajdlinux** [comment]
So, it looks like we're dropping support for the fd.o fork.

**Comment by ajdlinux** [comment]
@ruscur how close do you think we are to merging this?

**Comment by ajdlinux** [comment]
DONE!
