### ISSUE TITLE
Multiple component support / running different tests depending on patch tags

### ISSUE THREAD

**Issue by ruscur** [ruscur/snowpatch#3]
A project can have multiple sections.  For projects on GitHub, this can mean different repositories under an organisation.  For something like the Linux kernel, it can mean different architectures or subsystems.  If we can detect a patch is targeting a subsystem, we should have a way to run tests specific to that subsystem.

See also:
* proposal for Patchwork labels support - https://github.com/getpatchwork/patchwork/issues/22
* Patchwork subject prefixes API support: http://patchwork.ozlabs.org/patch/730319/

**Comment by ajdlinux** [comment]
We need to work out how to define components, how to define which tests to run for each component, and how to assign a patch/series to a component. There are a few design decisions we have to make here - can a patch belong to multiple components? How complex do we want our component-detecting heuristics to be?

**Comment by ruscur** [comment]
I think we want them to be dumb as hell and use patchwork's componenting support, which I thought was a thing that it had

needs investigation!

**Comment by ajdlinux** [comment]
@ruscur did you find out anything about component-ing in Patchwork?

**Comment by ruscur** [comment]
I don't think it's a thing upstream

**Comment by ajdlinux** [comment]
Well, could we usefully extend the existing delegation rule framework in Patchwork for this?

**Comment by ruscur** [comment]
we would need to discuss on the list whether the place for this is in patchwork or snowpatch.  that philosophy is probably different from fdo

**Comment by ajdlinux** [comment]
See also: https://github.com/getpatchwork/patchwork/issues/22
