### ISSUE TITLE
Publishing test logs externally

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#30]
Patchwork allows a URL to be specified for each Check. It seems that the intention is for only a short description of the check to be published in Patchwork itself, with additional information to be posted elsewhere and linked. This would be appropriate for posting test logs.

At the moment, our plan is to set this URL to the Jenkins console log. This is fine if the Jenkins setup is publicly accessible or the only people monitoring Checks on Patchwork have access to the Jenkins setup, but is probably not all that useful for the majority of use cases.

We should allow some alternative methods of publishing information from Jenkins externally, such as publishing the Jenkins log on a "pastebin" site. This could be done by allowing the user to configure an external command to which we can pipe the log from Jenkins.

**Comment by ajdlinux** [comment]
@ruscur any thoughts on this?

**Comment by ruscur** [comment]
add an "expose Jenkins logs" option to the settings (probably on by default?) - if so, link to the jenkins job console output

for internal jenkinses we could also take the jenkins logs and poop it to pastebin or something but i don't think we want to do that

:melon:

**Comment by ajdlinux** [comment]
ACK to having an option to link to the Jenkins logs

For publishing externally - how about we fetch the log, pipe it to a script specified by `log_publish_command` or something, which would return a URL for us to publish - something along the lines of the `ibmpastebin` script we use inside OzLabs.

**Comment by ruscur** [comment]
Yeah I was thinking that as well, however users might not want to have their logs, which probably expose internal infrastructure details, exposed to the internet.  So there's three options:

1. don't send any logs to patchwork
2. link directly to a publicly facing jenkins
3. link to a pastebin'd log of a private jenkins

If we want to support the latter we'd need 2 settings for it, I think.  We could have a separate option for using a pastebin service, since maybe people would regularly clean old jobs from their Jenkinses.

**Comment by ajdlinux** [comment]
Agreed about exposing internal infrastructure details.

I'm strongly in favour of supporting option 3 - one of the main reasons for snowpatch's design as an independent application rather than a Jenkins plugin is to deal with the issues that come with having private CI infrastructure that can't be publicly exposed to the internet.

I'd like to have a method for individual jobs to expose a custom log that's not just the Jenkins console output. This would allow each job to do whatever custom post-processing it wants. It probably wouldn't be too hard to do this by exposing an artifact with a designated name? However implementing this isn't our very highest priority right now.

**Comment by ruscur** [comment]
slap it on the to-do list

:tangerine:

**Comment by ajdlinux** [comment]
This is becoming more urgent now that we're setting up an internally facing Jenkins ourselves.

@ruscur apparently I had the same idea 2 years ago as what I was saying today

**Comment by ajdlinux** [comment]
I propose we add an optional configuration option, `publish_command`, that will consist of a path to an executable which takes one argument, namely the Jenkins result URL, and outputs a public URL on stdout.

snowpatch will execute this just before posting results, and will push the public URL to Patchwork.

This will probably require #46 to be fixed, as I imagine we'll want to point the script to a specific artifact, not a generic job page.

Open questions:
* do we need to make this option per-job, or is global sufficient?
* do we need to cope with multiple artifacts? (We already have a few multi-artifact jobs going)
