### ISSUE TITLE
Jenkins authentication

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#33]

**Comment by ruscur** [comment]
So if you log in to Jenkins and go to your settings you can get an API token.  This is why you can set a token in the settings when I wrote it eons ago.

We don't use it, though.

The docs seem to suggest that we can use basic auth with username=username and password=token and it'll work, so we just need to fit that into the jenkins abstraction

**Comment by ruscur** [comment]
but maybe <url>?token=<token> is enough? the docs are garbage

https://wiki.jenkins-ci.org/display/JENKINS/Authenticating+scripted+clients

**Comment by ajdlinux** [comment]
Patch submitted.
