### ISSUE TITLE
Allow specification of Jenkins artifact to use as log source rather than console log

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#38]
Linking users to a full Jenkins console log to explain why a check failed isn't always entirely helpful, as the console log usually contains a lot of stuff that's irrelevant to understanding the check.

Allow each job to specify the name of a Jenkins artifact, e.g. "snowpatch.log", so that the Jenkins job can direct relevant test output to this file.

**Comment by ruscur** [comment]
commit 647d68321faa1a90a6c083ce2ae9468469f71416 in upstream-wip

**Comment by ajdlinux** [comment]
Fixed in https://github.com/ruscur/snowpatch/commit/0df8f61113a50a986f6781f53d06f46ddd6cb048 in master
