### ISSUE TITLE
migrate from rustc_serialize to serde

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#39]
`rustc_serialize`, for various reasons, is semi-deprecated. `serde` is the anointed successor.

`serde` is significantly more flexible than `rustc_serialize` and allows us to do a few things that make our (de)serialisation code just a little bit neater.

The only reason to avoid `serde` right now is that its derivation features depend on "Macros 1.1", which is currently only in nightly (see https://github.com/rust-lang/rust/issues/35900 - it looks like it will be stabilised sometime quite soon). There is a workaround for stable compilers but it's quite messy. Hopefully, it should work fine with Rust 1.15 (the RFC won't be accepted in time for 1.14).

The only thing we still need `rustc_serialize` for is `docopt`, which doesn't support `serde` yet - this is being tracked at https://github.com/docopt/docopt.rs/issues/128.

See https://github.com/ajdlinux/snowpatch/tree/serde for my progress on this.

**Comment by ruscur** [comment]
looks really good

the day 1.15 comes out we merge this
