### ISSUE TITLE
Document alternatives to snowpatch

### ISSUE THREAD

**Issue by ruscur** [ruscur/snowpatch#4]
snowpatch isn't unique in the patch/CI space, we should mention Zuul and Gerrit somewhere which may be a better solution for people who stumble onto snowpatch.

In addition, it'd be good if we can document why we're going in a different direction from that (i.e. the patchwork mantra of "supplement mailing lists, not replace them")

**Comment by ajdlinux** [comment]
It'd be good if we at least hint at why we're not just writing this as a Jenkins plugin too

**Comment by ajdlinux** [comment]
@ruscur you seem better able to do this than I
