### ISSUE TITLE
Maintainer approval of patches before running dangerous tests

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#40]
We're testing code sent by untrusted parties over the internet. This is rather dangerous, especially when some of your tests involve running firmware or kernel code on bare-metal hardware, where a malicious or even just buggy patch can brick expensive hardware.

We should allow the configuration to specify tests that are potentially dangerous and require maintainer approval before running them.

@ruscur, thoughts on potentially using https://github.com/getpatchwork/patchwork/issues/22 as the method for maintainers approving patches as good-to-go?

**Comment by ruscur** [comment]
yeah I think that's a clever way to go about it.  in order to do this we would need an events API I would think - otherwise if a maintainer tags a really old patch as "pls test hard" we're not going to see that if it's not recent in the patches list.
