### ISSUE TITLE
Document snowpatch's own patchwork

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#5]
We should link to russell.cc/patchwork, or whichever patchwork we end up settling on (which I imagine will either be russell.cc or perhaps patchwork-beta.ozlabs.org if that becomes a thing)

**Comment by ajdlinux** [comment]
@ruscur wants to keep russell.cc as a testing environment, so we'll try and get ourselves on patchwork.ozlabs.org. Hopefully ozlabs.org gets the REST API sooner rather than later...

**Comment by ruscur** [comment]
Series support has been posted to the "stable" Patchwork list, so who knows

**Comment by ajdlinux** [comment]
We now use patchwork.ozlabs.org, patch sent to include that in docs
