### ISSUE TITLE
Support keeping patch/series branches around after tests

### ISSUE THREAD

**Issue by ajdlinux** [ruscur/snowpatch#55]
Some maintainers/developers would like to have the git branch we create stick around, at least for a while, as it's useful to look at.

On the other hand, if we have git repositories around with thousands of branches, it causes performance issues.

Options include:
- Separate "archive" repository vs "working" repository, working is kept clean, archive is more permanent (perhaps pruned using a cron job to delete branches older than X days, etc)
- ???

**Comment by ajdlinux** [comment]
@ruscur to enable maintainers to use a cronjob I think we should just add a config switch to turn off branch deletion, thoughts?

**Comment by ruscur** [comment]
works for me.
