### ISSUE TITLE
Test suite and CI setup

### ISSUE THREAD

**Issue by shenki** [ruscur/snowpatch#6]
![2f17a7eb-9061-4169-a185-296f73535d92](https://cloud.githubusercontent.com/assets/207355/14210738/d9a3568a-f871-11e5-9659-e6f6bc7db1ee.jpg)

**Comment by ruscur** [comment]
It does, badly.  We can run snowpatch on the snowpatch list (and we will), but before that we need tests, and testing snowpatch is difficult.

We essentially need three things:

- a mock Patchwork server (which is easy)
- a mock Jenkins server (which is a little more difficult, but still easy)
- a mock git repository (which concerns me).

I'm not sure how to go about having a mock git repository to do things to.  We could make a separate repository and require some setup for tests to work, or have it within the repository as a submodule, or have it within the module as not a submodule (which sounds awful), or have a directory and have the tests gitify it (i.e. call `git init`).

I think the submodule route would be the least gross, unless I'm missing something obvious. @ajdlinux thoughts?

**Comment by shenki** [comment]
Running a full end-to-end system test would be cool. It would also be great to use as a demo site for people wanting to check it out.

In the mean time could start with just building the code, as #7 does. If you plan to write some unit tests then they could be run there too.
