### ISSUE TITLE
Re-use the same branch for each patch in the series

### ISSUE THREAD

**Issue by ruscur** [ruscur/snowpatch#60]
Currently when we're testing each patch in the series, we'll try to apply it to each branch in order.  If it's the 4th branch, we waste time trying to apply it to branches 1, 2 and 3 for every patch in the series.  Would be better if we figured it out once and then stuck with that.

**Comment by mpe** [comment]
It would make even more sense to just apply the entire series once, and then build each commit.

**Comment by ruscur** [comment]
I think that would add some slight complexity to our Jenkins jobs (i.e. another parameter to track) but I don't think it's a big deal overall.  The one thing (I can currently think of) that we would lose is the ability to test earlier patches in a series when the later ones don't apply (this happens surprisingly often) but given that realistically we never do much actual testing on incomplete series it doesn't matter.

So we probably should've done it that way from the beginning.
