### ISSUE TITLE
Add contributing document

### ISSUE THREAD

**Issue by shenki** [ruscur/snowpatch#9]
It should mention that patch submission via the mailing list is preferred

**Comment by ajdlinux** [comment]
The readme already mentions that patch submission is the correct mechanism though perhaps could be clearer?

**Comment by shenki** [comment]
Github has a feature where a link to CONTRIBUTING.md is displayed when submitting pull requests or opening issues:

 https://github.com/blog/1184-contributing-guidelines

If we had one of those, I might have known that you'd prefer patches over PRs :)

**Comment by ajdlinux** [comment]
Ah, of course. I wouldn't know that, I hardly ever make pull requests ;)

**Comment by ajdlinux** [comment]
Am working on this - any other information that we want to include at this stage? @ruscur

**Comment by ruscur** [comment]
Maybe link to some article on `git send-email` for dummies, and just lift stuff out of the README.  Update the README to just say "here's the mailing list, see CONTRIBUTING.md".

Anyone interested in snowpatch is probably already used to patches, so...

**Comment by ajdlinux** [comment]
Any coding style guides we want to refer to?

**Comment by ruscur** [comment]
Yeah, we can link to the existing Rust style guide (https://aturon.github.io), noting that fixing any non-compliant existing code would make for a good patch.
